# Generated by Django 3.1.1 on 2020-09-11 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NES',
            new_name='NintendoEntertainementSystem',
        ),
    ]
