# Generated by Django 3.1.1 on 2020-09-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environement', '0002_auto_20200911_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nintendoentertainementsystem',
            options={'verbose_name': 'Nintendo Entertainement System', 'verbose_name_plural': 'Nintendo Entertainement System'},
        ),
        migrations.RenameField(
            model_name='nintendoentertainementsystem',
            old_name='console',
            new_name='rom',
        ),
    ]
